### ISSUE TITLE
Credit me?

### ISSUE THREAD

**Issue by polymeris** [denisidoro/floki#43]
Hello,

Looking at [the initial commit](https://github.com/denisidoro/floki/commit/88fd66e75ba4770c0fc134948aa335bc4c81af3d#diff-0fff143854a4f5c0469a3819b978a483R20) I see floki is based on my [hello-react-blessed gist](https://gist.github.com/polymeris/5e117676b79a505fe777df17f181ca2e). Of course you have taken this to a whole other level, but would you mind crediting me for the original implementation/idea?

**Comment by denisidoro** [comment]
Yes, sure! I haven't contributed to this project for some time but I'll try to do so next week

**Comment by polymeris** [comment]
Thanks!
