### ISSUE TITLE
Support transit encoded EDN

### ISSUE THREAD

**Issue by dazld** [denisidoro/floki#46]
EDN seems to be rare as a wire format - might be wrong, but seems transit is more common as an encoding for sending EDN over the wire. 

Floki doesn't currently understand transit though, which means it can't directly consume the output of APIs that speak transit.

**Comment by denisidoro** [comment]
It should be pretty easy to support transit: we simply need to call something like `(transit-str->edn ...)` in here: https://github.com/denisidoro/floki/blob/master/src/floki/core.cljs#L32
